# Generated by Django 5.0 on 2024-04-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managermodule', '0002_alter_roomdetails_no_of_rooms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roomdetails',
        ),
    ]
